--liquibase formatted sql

--changeset adlan:add_file
CREATE TABLE files
(
    id            BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    upload_status VARCHAR,
    id_file       BIGINT,
    updated_at    TIMESTAMP WITH TIME ZONE                            NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE                            NOT NULL DEFAULT NOW()
);
