spring:
 datasource:
  url: jdbc:postgresql://localhost:5432/training_1
  username: 'Adlan'
  password: ''
 liquibase:
  change-log: "classpath:config/liquibase/master.xml"
 security:
  swagger-ui:
   username: 'swagger'
   password: 'OpenAPI!9devxUt7pLsaQPWu'

springdoc:
 swagger-ui:
  disable-swagger-default-url: true
  config-url: '/v3/api-docs/swagger-config'
  url: '/v3/api-docs'
  path: '/swagger-ui'
